example:
  property: "I AM IN THE DEFAULT"
spring:
  jpa:
    database: mysql
    platform: mysql
    show-sql: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/ms?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root

redis:
  server: "redis"
  port: "6379"

signing:
  key: "345345fsdfsf5345"
